# generated by datamodel-codegen:
#   filename:  playback/playback_file.json
#   timestamp: 2022-01-23T15:49:03+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class PlaybackOfFile(BaseModel):
    id: Optional[str] = Field(None, title='Playback ID')
    time_stamp: Optional[str] = Field(
        None,
        description='Current timestamp from recording/log files.',
        title='Current timestamp',
    )
    timeline_position: Optional[float] = Field(
        None,
        description='Current frame/row relative time position of total playback interval steps.',
        title='Timeline position',
    )
    duration: Optional[float] = Field(
        None,
        description='Total duration in seconds for whole log/recording.',
        title='Duration',
    )
    is_playing: Optional[bool] = Field(
        None,
        description='Boolean value if playback is ongoing[true] or paused[false].',
        title='Playing',
    )
