# generated by datamodel-codegen:
#   filename:  observations/ais.json
#   timestamp: 2022-01-12T08:16:31+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field

from ..core import position


class Class(Enum):
    A = 'A'
    B = 'B'


class NavigationalStatus(Enum):
    Under_way_using_engine = 'Under way using engine'
    At_anchor = 'At anchor'
    Not_under_command = 'Not under command'
    Restricted_maneuverability = 'Restricted maneuverability'
    Constrained_by_her_draught = 'Constrained by her draught'
    Moored = 'Moored'
    Aground = 'Aground'
    Engaged_in_fishing = 'Engaged in fishing'
    Under_way_sailing = 'Under way sailing'
    High_speed_craft = 'High-speed craft'
    Wing_in_ground = 'Wing in ground'
    Power_driven_vessel_towing_astern__regional_use_ = (
        'Power-driven vessel towing astern (regional use)'
    )
    Power_driven_vessel_pushing_ahead_or_towing_alongside__regional_use_ = (
        'Power-driven vessel pushing ahead or towing alongside (regional use)'
    )
    Reserved = 'Reserved'
    AIS_SART__MOB_AIS__EPIRB_AIS = 'AIS-SART, MOB-AIS, EPIRB-AIS'
    Undefined = 'Undefined'


class PositionAccuracy(Enum):
    high = 'high'
    low = 'low'


class AisVessel(BaseModel):
    sensor_id: str = Field(..., title='Physical sensor id')
    timestamp: datetime = Field(
        ...,
        description='Date and time when the message was received, expressed according to the ISO 8601 standard.',
        title='Timestamp of AIS message',
    )
    mmsi: int = Field(
        ..., description='MMSI number of the AIS transceiver.', title='MMSI'
    )
    class_: Class = Field(
        ...,
        alias='class',
        description='Class of the AIS transceiver, defined by the AIS messages communicating the data of the vessel (A: messages 1,2,3, and 5; B: messages 18, 19, and 24).',
        title='class',
    )
    position: position.Position
    heading: Optional[float] = Field(
        None,
        description='Heading of the vessel with respect to True North [degrees]',
        title='Heading',
    )
    sog: Optional[float] = Field(
        None, description='Speed Over Ground of the vessel [knots].', title='SOG'
    )
    cog: Optional[float] = Field(
        None,
        description='Course Over Ground of the vessel with respect to True North [degrees]',
        title='COG',
    )
    rate_of_turn: Optional[float] = Field(
        None,
        description='Rate of turn of the vessel [degrees/minute], positive to starboard',
        title='Rate of turn',
    )
    imo_number: Optional[int] = Field(
        None, description='IMO number of the vessel', title='IMO number'
    )
    draught: Optional[float] = Field(
        None, description='Draught of the vessel [m]', title='Draught'
    )
    navigational_status: Optional[NavigationalStatus] = Field(
        None,
        description='Navigational status the vessel, enum values according to AIS specification',
        title='Navigational status',
    )
    type_and_cargo: Optional[int] = Field(
        None,
        description='Type and cargo indicator of the vessel, according to: https://www.navcen.uscg.gov/pdf/AIS/AISGuide.pdf',
        title='Type and cargo indicator',
    )
    ship_name: Optional[str] = Field(
        None, description='The name of this vessel', title='Ship name'
    )
    call_sign: Optional[str] = Field(
        None, description='The call sign of this vessel', title='Call sign'
    )
    destination: Optional[str] = Field(
        None, description='The destination of this vessel', title='Destination'
    )
    eta: Optional[datetime] = Field(
        None,
        description='The ETA to `destination` of this vessel, expressed according to the ISO 8601 standard.',
        title='ETA',
    )
    loa: Optional[float] = Field(
        None,
        description='The length over all (LOA) of this vessel [m]',
        title='Length Over All',
    )
    beam: Optional[float] = Field(
        None, description='The beam of this vessel [m]', title='Beam'
    )
    position_accuracy: Optional[PositionAccuracy] = Field(
        None,
        description='Accuracy of the position (high <= 10 meters; low > 10 meters).',
        title='Position accuracy',
    )
