# generated by datamodel-codegen:
#   filename:  observations/ground_velocity.json
#   timestamp: 2022-01-12T08:16:31+00:00

from __future__ import annotations

from pydantic import BaseModel, Field

from ..core import location


class GroundVelocity(BaseModel):
    sensor_id: str = Field(..., title='Physical sensor id')
    location: location.Location = Field(
        ...,
        description='Location of the reporting sensor in the BF frame of reference.',
    )
    sog: float = Field(
        ...,
        description='Reported speed over ground.',
        title='Speed over ground [knots]',
    )
    cog: float = Field(
        ...,
        description='Reported course over ground [degrees] relative True North',
        title='Course over ground',
    )
