# generated by datamodel-codegen:
#   filename:  observations/heading.json
#   timestamp: 2022-01-12T08:16:31+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class Type(Enum):
    Magnetic = 'Magnetic'
    True_ = 'True'


class Heading(BaseModel):
    sensor_id: str = Field(..., title='Physical sensor id')
    heading: float = Field(
        ..., description='Heading, relative to North [degrees]', title='Heading'
    )
    type: Type = Field(..., title='Type of sensor')
