# generated by datamodel-codegen:
#   filename:  observations/lidar.json
#   timestamp: 2022-01-23T15:49:03+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from ..core import location, rotation


class LIDAR(BaseModel):
    sensor_id: str = Field(..., title='Physical sensor id')
    location: location.Location = Field(
        ...,
        description='Location of the reporting sensor in the BF frame of reference.',
    )
    rotation: rotation.Rotation = Field(
        ...,
        description='Rotation of the reporting sensor in the BF frame of reference.',
    )
    points: List = Field(
        ...,
        description='Points captured by the LIDAR sensor as a list of (x,y,z) points [m] in a right-handed, cartesian frame of reference defined by `location` and `rotation` in relation to the BF frame of reference.',
        examples=[[0.0, 0.0, 0.0], [0.0, 1.0, 0.0]],
        title='Points',
    )
