# generated by datamodel-codegen:
#   filename:  observations/rate_of_turn.json
#   timestamp: 2022-01-23T15:49:03+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class RateOfTurn(BaseModel):
    sensor_id: str = Field(..., title='Physical sensor id')
    rot: float = Field(
        ...,
        description='Rate of turn [degrees/minute], positive to starboard',
        title='Rate of turn',
    )
