# generated by datamodel-codegen:
#   filename:  ownship/pilot_card.json
#   timestamp: 2022-01-23T15:49:03+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class NavigationalStatus1(Enum):
    Under_way_using_engine = 'Under way using engine'
    At_anchor = 'At anchor'
    Not_under_command = 'Not under command'
    Restricted_maneuverability = 'Restricted maneuverability'
    Constrained_by_her_draught = 'Constrained by her draught'
    Moored = 'Moored'
    Aground = 'Aground'
    Engaged_in_fishing = 'Engaged in fishing'
    Under_way_sailing = 'Under way sailing'
    High_speed_craft = 'High-speed craft'
    Wing_in_ground = 'Wing in ground'
    Power_driven_vessel_towing_astern__regional_use_ = (
        'Power-driven vessel towing astern (regional use)'
    )
    Power_driven_vessel_pushing_ahead_or_towing_alongside__regional_use_ = (
        'Power-driven vessel pushing ahead or towing alongside (regional use)'
    )
    Reserved = 'Reserved'
    AIS_SART__MOB_AIS__EPIRB_AIS = 'AIS-SART, MOB-AIS, EPIRB-AIS'
    Undefined = 'Undefined'


class PilotCard(BaseModel):
    vessel_model_id: str = Field(..., title='Physical sensor id')
    updated: datetime = Field(
        ...,
        description='Date and time when the vessel model data where edited or updated.',
        title='Timestamp of last edit',
    )
    steering_units: Optional[List[Dict[str, Any]]] = Field(
        None, description='Description of steering units', title='Steering unit'
    )
    mmsi: Optional[int] = Field(
        None, description='MMSI number of the AIS transceiver.', title='MMSI'
    )
    imo_number: Optional[int] = Field(
        None, description='IMO number of the vessel', title='IMO number'
    )
    navigational_status: Optional[NavigationalStatus1] = Field(
        None,
        description='Navigational status the vessel, enum values according to AIS specification',
        title='Navigational status',
    )
    type_and_cargo: Optional[int] = Field(
        None,
        description='Type and cargo indicator of the vessel, according to: https://www.navcen.uscg.gov/pdf/AIS/AISGuide.pdf',
        title='Type and cargo indicator',
    )
    ship_name: Optional[str] = Field(
        None, description='The name of this vessel', title='Ship name'
    )
    call_sign: Optional[str] = Field(
        None, description='The call sign of this vessel', title='Call sign'
    )
    loa: Optional[float] = Field(
        None,
        description='The length over all (LOA) of this vessel [m]',
        title='Length Over All',
    )
    beam: Optional[float] = Field(
        None, description='The beam of this vessel [m]', title='Beam'
    )
