# generated by datamodel-codegen:
#   filename:  ownship/steering_unit.json
#   timestamp: 2022-01-23T15:49:03+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

from ..core import location


class SteeringUnit(BaseModel):
    unit_id: str = Field(..., title='Unit id')
    location: Optional[location.Location] = Field(
        None, description='Location of the rudder in the BF frame of reference.'
    )
    readable_id: Optional[str] = Field(None, title='Readable id')
    angle_max: Optional[float] = Field(
        35.0,
        description='Rudder angle in degrees, positive when trailing edge points to port',
        title='Rudder angle',
    )
    angle_min: Optional[float] = Field(
        -35.0,
        description='Rudder angle in degrees, positive when trailing edge points to port',
        title='Rudder angle',
    )
    flap_angle_max: Optional[float] = Field(
        15.0,
        description='Rudder flap angle in degrees, positive when trailing edge points to port',
        title='Rudder flap angle',
    )
    flap_angle_min: Optional[float] = Field(
        -15.0,
        description='Rudder flap angle in degrees, positive when trailing edge points to port',
        title='Rudder flap angle',
    )
