# generated by datamodel-codegen:
#   filename:  core/pose.json
#   timestamp: 2022-01-12T08:16:31+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra

from . import attitude, position


class Pose(BaseModel):
    class Config:
        extra = Extra.forbid

    position: position.Position
    attitude: attitude.Attitude
