# generated by datamodel-codegen:
#   filename:  core/wrench.json
#   timestamp: 2022-01-12T08:16:31+00:00

from __future__ import annotations

from pydantic import BaseModel, Extra

from . import force, moment


class Wrench(BaseModel):
    class Config:
        extra = Extra.forbid

    force: force.Force
    moment: moment.Moment
